name: pact_consumer_dart
version: 0.1.3
description: >
  Pact consumer library implemented in dart. This library is platform agnostic and depends on w_transport.
authors:
  - Tom Evans <thomas.evans@workiva.com>
homepage:
  https://github.com/thomaslevans-wf/pact_consumer_dart

environment:
  sdk: ">=2.2.2 < 3.0.0"

dependencies:
  w_transport: "^3.2.8"

dev_dependencies:
  coverage: "^0.13.3"
  dart_dev: "^3.2.1"
  dart_style: "^1.3.1"
  test: "^1.9.1"

transformers:
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
